---
# tasks file for k8s_initial
   - name: install Docker
     yum:
       name: docker
       state: present
       update_cache: true

   - name: start Docker
     service:
       name: docker
       state: started


   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: install kubelet
     yum:
        name: kubelet
        state: present
        update_cache: true

   - name: install kubeadm
     yum:
        name: kubeadm
        state: present

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started
  
   - name: install kubectl
     yum:
         name: kubectl
         state: present
         allow_downgrade: yes

 
   - name: creating daemon.json
     blockinfile:
              path: "/etc/docker/daemon.json"
              create: yes
              marker: ""
              block:
                "{\n \"exec-opts\": [\"native.cgroupdriver=systemd\"]\n}"
   
   - name: Restarting docker services 
     service:
       name: docker
       enabled: yes
       state: restarted
   
   - name: iproutes-tc
     package:
       name:  iproute-tc
       state: present
